# Simpsons - Soluciones

In [47]:
import pandas as pd

## Leemos todos los ficheros y nos aseguramos de que están bien leídos

In [48]:
characters = pd.read_csv('characters.csv', sep=';')
episodes = pd.read_csv('episodes.csv', sep=';')
locations = pd.read_csv('locations.csv', sep=';')
scripts = pd.read_csv('scripts.csv', sep=';')

In [49]:
characters.head(1)

   id      name normalized_name gender
0   7  Children        children    NaN

In [150]:
episodes.tail(10)

,id,title,original_air_date,production_code,season,number_in_season,number_in_series,us_viewers_in_millions,views,imdb_rating,imdb_votes,image_url,video_url
590,429,Lisa the Drama Queen,2009-01-25,KABF22,20,9,429,5.75,38582.0,5.9,706.0,http://static-media.fxx.com/img/FX_Networks_-_...,http://www.simpsonsworld.com/video/292944963870
591,431,How the Test Was Won,2009-03-01,LABF02,20,11,431,6.52,41271.0,7.0,603.0,http://static-media.fxx.com/img/FX_Networks_-_...,http://www.simpsonsworld.com/video/277134915702
592,434,In the Name of the Grandfather,2009-03-22,LABF11,20,14,434,6.15,45727.0,6.3,619.0,http://static-media.fxx.com/img/FX_Networks_-_...,http://www.simpsonsworld.com/video/307849283838
593,435,Wedding for Disaster,2009-03-29,LABF05,20,15,435,6.58,43254.0,6.8,571.0,http://static-media.fxx.com/img/FX_Networks_-_...,http://www.simpsonsworld.com/video/273024579646
594,486,The Ned-Liest Catch,2011-05-22,NABF15,22,22,486,5.25,43681.0,7.0,492.0,http://static-media.fxx.com/img/FX_Networks_-_...,http://www.simpsonsworld.com/video/255101507699
595,500,At Long Last Leave,2012-02-19,PABF07,23,14,500,5.77,45226.0,7.0,580.0,http://static-media.fxx.com/img/FX_Networks_-_...,http://www.simpsonsworld.com/video/230541891832
596,502,How I Wet Your Mother,2012-03-11,PABF08,23,16,502,4.97,44818.0,7.3,541.0,http://static-media.fxx.com/img/FX_Networks_-_...,http://www.simpsonsworld.com/video/230597187582
597,511,Adventures in Baby-Getting,2012-11-04,PABF18,24,3,511,5.65,39687.0,6.9,460.0,http://static-media.fxx.com/img/FX_Networks_-_...,http://www.simpsonsworld.com/video/221688899646
598,542,Diggs,2014-03-09,SABF08,25,12,542,2.69,39292.0,6.4,473.0,http://static-media.fxx.com/img/FX_Networks_-_...,http://www.simpsonsworld.com/video/310529091639
599,548,Days of Future Future,2014-04-13,SABF13,25,18,548,3.64,55742.0,7.0,504.0,http://static-media.fxx.com/img/FX_Networks_-_...,http://www.simpsonsworld.com/video/310257731892

In [51]:
locations.head(1)

   id    name normalized_name
0   1  Street          street

In [151]:
scripts.tail(10)

,id,episode_id,number,raw_text,timestamp_in_ms,speaking_line,character_id,location_id,spoken_words,normalized_text,word_count
157654,9539,32,199,Marge Simpson: Yes.,811000,True,1.0,373.0,Yes.,yes,1.0
157655,9540,32,200,Lisa Simpson: Can we do it this week?,812000,True,9.0,373.0,Can we do it this week?,can we do it this week,6.0
157656,9541,32,201,(Springfield Elementary School: INT. ELEMENTAR...,814000,False,NaN,3.0,NaN,NaN,NaN
157657,9542,32,202,"Lisa Simpson: (REHEARSING) Mr. Bergstrom, we r...",814000,True,9.0,3.0,"Mr. Bergstrom, we request the pleasure of your...",mr bergstrom we request the pleasure of your c...,33.0
157658,9543,32,203,"Miss Hoover: Good morning, Lisa.",829000,True,464.0,3.0,"Good morning, Lisa.",good morning lisa,3.0
157659,9544,32,204,Miss Hoover: (OFF LISA'S REACTION) I'm back.,831000,True,464.0,3.0,I'm back.,im back,2.0
157660,9545,32,205,"Miss Hoover: You see, class, my Lyme disease t...",839000,True,464.0,3.0,"You see, class, my Lyme disease turned out to ...",you see class my lyme disease turned out to be,10.0
157661,9546,32,206,Miss Hoover: Psy-cho-so-ma-tic.,842000,True,464.0,3.0,Psy-cho-so-ma-tic.,psy-cho-so-ma-tic,1.0
157662,9547,32,207,Ralph Wiggum: Does that mean you were crazy?,844000,True,119.0,3.0,Does that mean you were crazy?,does that mean you were crazy,6.0
157663,9548,32,208,"JANEY: No, that means she was faking it.",845000,True,4.0,3.0,"No, that means she was faking it.",no that means she was faking it,7.0

## ¿Cuál es la temporada con más episodios?

In [105]:
episodes.groupby('season')['season'].size().sort_values(ascending=False).head()

season
6    25
7    25
8    25
9    25
3    24
dtype: int64

## ¿Cual es la primera frase de la serie? ¿Quién la dice?

In [148]:
temp_one = episodes[(episodes.season == 1) & (episodes.number_in_season == 1)]
scripts_episode_one = pd.merge(scripts, episode_one, left_on='episode_id', right_on='id', suffixes=('_script', '_episode'))
scripts_spoken_one = scripts_episode_one[scripts_episode_one.speaking_line == True]
scripts_spoken_one.sort_values('number').head(1)

,id_script,episode_id,number,raw_text,timestamp_in_ms,speaking_line,character_id,location_id,spoken_words,normalized_text,...,production_code,season,number_in_season,number_in_series,us_viewers_in_millions,views,imdb_rating,imdb_votes,image_url,video_url
2,3,1,2,"Marge Simpson: Ooo, careful, Homer.",8000,True,1.0,2.0,"Ooo, careful, Homer.",ooo careful homer,...,7G08,1,1,1,26.7,171408.0,8.2,3734.0,http://static-media.fxx.com/img/FX_Networks_-_...,http://www.simpsonsworld.com/video/273376835817

## ¿Cuáles son los 10 personajes que más hablan en los episodios?

In [134]:
character_lines = pd.merge(characters, scripts[scripts.speaking_line == True], left_on='id', right_on='character_id', suffixes=('_char', '_script'))
character_lines.groupby('name').size().sort_values(ascending=False).head(10)

name
Homer Simpson          28059
Marge Simpson          13233
Bart Simpson           13145
Lisa Simpson           10854
C. Montgomery Burns     3116
Moe Szyslak             2808
Seymour Skinner         2381
Ned Flanders            2007
Grampa Simpson          1875
Milhouse Van Houten     1798
dtype: int64

## ¿Cuáles son las 10 localizaciones más recurrentes en los episodios?

In [130]:
location_lines = pd.merge(locations, scripts, left_on='id', right_on='location_id', suffixes=('_location', '_script'))
location_lines.groupby('name').size().sort_values(ascending=False).head(10)

name
Simpson Home                       34952
Springfield Elementary School       7047
Moe's Tavern                        4599
Springfield Nuclear Power Plant     3589
Kwik-E-Mart                         1476
First Church of Springfield         1416
Simpson Living Room                 1378
Springfield Street                  1301
Springfield                         1301
Simpson Car                         1234
dtype: int64

## ¿Cuál es el mejor episodio según IMDB?

In [137]:
episodes.sort_values('imdb_rating', ascending = False).head()[['title','imdb_rating','imdb_votes']]

                                      title  imdb_rating  imdb_votes
537                           Homer's Enemy          9.2      2256.0
535                     You Only Move Twice          9.2      2439.0
323  The City of New York vs. Homer Simpson          9.1      1918.0
534          Who Shot Mr. Burns? (Part One)          9.1      1619.0
261                Last Exit to Springfield          9.0      1827.0

## ¿Cuál es la mejor temporada (en media) según IMDB?

In [142]:
episodes.groupby('season')['imdb_rating'].mean().sort_values(ascending=False).head()

season
5    8.336364
7    8.324000
6    8.312000
4    8.268182
8    8.220000
Name: imdb_rating, dtype: float64

## ¿Cuál es la localización preferida de Bart?

## ¿Cuál es el episodio más visto en USA?

In [143]:
episodes.sort_values('us_viewers_in_millions', ascending = False).head()[['title','us_viewers_in_millions']]

                     title  us_viewers_in_millions
2         Bart Gets an "F"                    33.6
217  Life on the Fast Lane                    33.5
218    The Crepes of Wrath                    31.2
1       Krusty Gets Busted                    30.4
0        Homer's Night Out                    30.3

## ¿Cuál es el personaje que más veces habla el primero en los episodios?

## ¿Cuales son las 25 palabras más utilizadas por Homer?

## ¿Cuál es el episodio con más personajes involucrados? ¿Y el que menos?

## ¿Cuál es el episodio con más lineas de diálogo? ¿Y el que menos?

## ¿En qué episodio aparece por primera vez Krusty?